import Head from 'next/head'
import { NoWalletButton } from '@components/Web3';
import Link from 'next/link';
import { useMoralis } from 'react-moralis';
import { Footer, Example} from '@components/index';
import { classNames } from '@helpers/ui';
import { Hero } from './components';


interface HomeProps {
    isAuthenticated?: boolean;
}

const HomeView = () => {
    
    const { isAuthenticated } = useMoralis();

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            { !isAuthenticated && <>
                <Hero isAuthenticated={isAuthenticated} />
            </>}

            { isAuthenticated && <>
                <Example isAuthenticated={isAuthenticated} />
            </>}
        </>
    )
}



export default HomeView

